modLoader="javafml"
loaderVersion="[1,)"
license="LGPL 2.1"
[[mods]]
modId="cobblefordays"
version="${version}"
displayName="Cobble For Days"
authors="Lex"
description="A set of simple cobblestone generators. Mainly useful for servers that don't want multi-block cobblegens."